"""
DNSKit
Copyright (C) Ian Spence and other DNSKit Contributors

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""
import http.client
import os
import sys
import io

pages = []

connection = http.client.HTTPSConnection("www.unicode.org")
connection.request("GET", "/Public/idna/latest/IdnaMappingTable.txt")
response = connection.getresponse()
text_stream = io.TextIOWrapper(response, encoding="utf-8")
line_n = 0
for line in text_stream:
    line_n += 1
    line = line.rstrip()
    if not line:
        continue

    if line[0] == "#" or line == "":
        continue

    # Line structure:
    # Num   Field              Description
    # 0     Code point(s)      Hex value or range of values.
    # 1     Status             valid, ignored, mapped, deviation, or disallowed
    # 2     Mapping            Hex value(s). Only present if the Status is ignored, mapped, or
    #                          deviation.
    # 3     IDNA2008 Status    There are two values: NV8 and XV8. NV8 is only present if the
    #                          Status is valid but the character is excluded by IDNA2008 from
    #                          all domain names for all versions of Unicode. XV8 is present when
    #                          the character is excluded by IDNA2008 for the current version of
    #                          Unicode. These are not normative values. 

    comment = ""

    parts = line.split('#')
    if len(parts) > 1:
        comment = parts[len(parts)-1]
        line = line.replace("# " + comment, "")
        line = line.replace("#" + comment, "")
    
    parts = line.split(';')
    if len(parts) < 2:
        print("Syntax error on line %d: too few columns" % (line_n))
        sys.exit(1)

    codePoints = parts[0].strip().split("..")
    if len(codePoints) == 1:
        codePoints.append(codePoints[0])

    page = int("0x%s" % codePoints[0], 0) >> 16

    status = parts[1].strip()
    if status != "valid" and status != "ignored" and status != "mapped" and status != "deviation" and status != "disallowed":
        print("Syntax error on line %d: invalid satatus '%s'" % (line_n, status))
        sys.exit(1)

    if status == "valid" or status == "deviation":
        continue

    mapping = []
    if len(parts) >= 3:
        for m in parts[2].split(" "):
            m = m.strip()
            if m == "":
                continue
            mapping.append("0x%s" % m)

    rule = {
        "codePoints": codePoints,
        "status": status,
        "mapping": mapping,
        "comment": comment,
    }

    if len(pages) == 0:
        pages.append({
            "page": page,
            "rules": []
        })

    last_page = pages[-1]
    if last_page["page"] == page:
        last_page["rules"].append(rule)
    else:
        pages.append({
            "page": page,
            "rules": [rule]
        })

def ruleToC(rule, replace_prefix):
    start = "0x%s" % rule["codePoints"][0]
    end = "0x%s" % rule["codePoints"][1]
    status = "idnarule_action_%s" % rule["status"]
    mapping = "NULL"
    if len(rule["mapping"]) > 0:
        mapping = "%s_replace" % replace_prefix

    return "{ %s, %s, %s, %d, %s }" % (start, end, status, len(rule["mapping"]), mapping)

with open('rules.c', 'w') as file:
    file.write("""// DNSKit
// Copyright (C) Ian Spence and other DNSKit Contributors
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// DO NOT EDIT THIS FILE
// This file is dynamically generated using the update_rules.py script
// The information in this file is sourced from
// https://www.unicode.org/Public/idna/latest/IdnaMappingTable.txt

#include "rules.h"

""")
    for page in pages:
        page_num = page["page"]
        rules = page["rules"]

        i = 0
        for rule in rules:
            if len(rule["mapping"]) > 0:
                file.write("const uint32_t page_%d_rule_%d_replace[%d] = {%s};\n" % (page_num, i, len(rule["mapping"]), ", ".join(rule["mapping"])))
            i += 1
        
        # const size_t page_0_rule_count = 72;
        file.write("const size_t page_%d_rule_count = %d;\n" % (page_num, len(rules)))
        file.write("const IDNARule page_%d_rules[] = {\n" % page_num)
        i = 0
        for rule in rules:
            file.write("  %s,\n" % ruleToC(rule, "page_%d_rule_%d" % (page_num, i)))
            i += 1
        file.write("};\n")

    file.write("\nconst IDNARule* find_idna_rules(uint32_t codepoint, size_t* rule_count) {\n")
    file.write("  switch (codepoint >> 16) {\n")
    for page in pages:
        page_num = page["page"]
        file.write("    case %d: {\n" % page_num)
        file.write("      *rule_count = page_%d_rule_count;\n" % page_num)
        file.write("      return (const IDNARule*)page_%d_rules;\n" % page_num)
        file.write("    }\n")
    file.write("  }\n\n")
    file.write("  *rule_count = -1;\n")
    file.write("  return NULL;\n")
    file.write("}\n")