name: Bug Report
description: "Found an issue with DNSKit? Let us know and we'll do our best to resolve it."
labels: ["bug"]
assignees:
  - ecnepsnai
body:
  - type: checkboxes
    id: existing_issues
    attributes:
      label: "Searched for Another Report"
      options:
        - label: "Confirm that you have already searched for another report of your bug"
  - type: input
    id: version
    attributes:
      label: "DNSKit version or revision:"
    validations:
      required: true
  - type: input
    id: device
    attributes:
      label: "Device Type and iOS, macOS, or iPadOS Version:"
    validations:
      required: true
  - type: textarea
    id: repro-steps
    attributes:
      label: "Describe the issue you are seeing, what did you expect, what happened instead:"
    validations:
      required: true
  - type: textarea
    id: expect-outcome
    attributes:
      label: "Provide code that can reproduce the issue:"
    validations:
      required: true
